version: '0.1'
services:
  mistral-chatbot-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot_db
      - FLASK_APP=smol.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - mongo
    networks:
      - agent_internal
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - name=value